name: SOPRANO Tests

on:
  pull_request:
    branches:
      - python
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    name: Development tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          channels: conda-forge
          python-version: 3.11
          activate-environment: soprano-dev
          environment-file: src/SOPRANO/ci_osx.yml  # additional coreutils
          use-mamba: true
      - name: Install SOPRANO
        run: |
          conda activate soprano-dev
          pip install -e .[ci]
      - name: Test conda environment
        run: |
          conda activate soprano-dev
          pytest -s tests/test_installation.py
      - name: Test units
        run: |
          conda activate soprano-dev
          pytest -s tests/test_units